In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
# import some data to play with
data = pd.read_csv('Company_Data.csv',index_col=0)
data = data.reset_index()

In [3]:
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [4]:
label_encoder = preprocessing.LabelEncoder()
data['Urban']= label_encoder.fit_transform(data['Urban']) 

In [5]:
label_encoder = preprocessing.LabelEncoder()
data['US']= label_encoder.fit_transform(data['US']) 

In [6]:
data=pd.get_dummies(data,columns=['ShelveLoc'], drop_first=True)
data

Sales  CompPrice  Income  Advertising  Population  Price  Age  Education  \
0     9.50        138      73           11         276    120   42         17   
1    11.22        111      48           16         260     83   65         10   
2    10.06        113      35           10         269     80   59         12   
3     7.40        117     100            4         466     97   55         14   
4     4.15        141      64            3         340    128   38         13   
..     ...        ...     ...          ...         ...    ...  ...        ...   
395  12.57        138     108           17         203    128   33         14   
396   6.14        139      23            3          37    120   55         11   
397   7.41        162      26           12         368    159   40         18   
398   5.94        100      79            7         284     95   50         12   
399   9.71        134      37            0          27    120   49         16   

     Urban  US  ShelveLoc_Good  ShelveLoc_Medium  
0        1   1               0                 0  
1        1   1               1                 0  
2        1   1               0                 1  
3        1   1               0                 1  
4        1   0               0                 0  
..     ...  ..             ...               ...  
395      1   1               1                 0  
396      0   1               0                 1  
397      1   1               0                 1  
398      1   1               0                 0  
399      1   1               1                 0  

[400 rows x 12 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Sales             400 non-null    float64
 1   CompPrice         400 non-null    int64  
 2   Income            400 non-null    int64  
 3   Advertising       400 non-null    int64  
 4   Population        400 non-null    int64  
 5   Price             400 non-null    int64  
 6   Age               400 non-null    int64  
 7   Education         400 non-null    int64  
 8   Urban             400 non-null    int32  
 9   US                400 non-null    int32  
 10  ShelveLoc_Good    400 non-null    uint8  
 11  ShelveLoc_Medium  400 non-null    uint8  
dtypes: float64(1), int32(2), int64(7), uint8(2)
memory usage: 29.0 KB


In [8]:
x=data.iloc[:,1:12]
y=data['Sales']

In [9]:
x

CompPrice  Income  Advertising  Population  Price  Age  Education  Urban  \
0          138      73           11         276    120   42         17      1   
1          111      48           16         260     83   65         10      1   
2          113      35           10         269     80   59         12      1   
3          117     100            4         466     97   55         14      1   
4          141      64            3         340    128   38         13      1   
..         ...     ...          ...         ...    ...  ...        ...    ...   
395        138     108           17         203    128   33         14      1   
396        139      23            3          37    120   55         11      0   
397        162      26           12         368    159   40         18      1   
398        100      79            7         284     95   50         12      1   
399        134      37            0          27    120   49         16      1   

     US  ShelveLoc_Good  ShelveLoc_Medium  
0     1               0                 0  
1     1               1                 0  
2     1               0                 1  
3     1               0                 1  
4     0               0                 0  
..   ..             ...               ...  
395   1               1                 0  
396   1               0                 1  
397   1               0                 1  
398   1               0                 0  
399   1               1                 0  

[400 rows x 11 columns]

In [10]:
y

0       9.50
1      11.22
2      10.06
3       7.40
4       4.15
       ...  
395    12.57
396     6.14
397     7.41
398     5.94
399     9.71
Name: Sales, Length: 400, dtype: float64

In [11]:
data['Sales'].unique()

array([ 9.5 , 11.22, 10.06,  7.4 ,  4.15, 10.81,  6.63, 11.85,  6.54,
        4.69,  9.01, 11.96,  3.98, 10.96, 11.17,  8.71,  7.58, 12.29,
       13.91,  8.73,  6.41, 12.13,  5.08,  5.87, 10.14, 14.9 ,  8.33,
        5.27,  2.99,  7.81, 13.55,  8.25,  6.2 ,  8.77,  2.67, 11.07,
        8.89,  4.95,  6.59,  3.24,  2.07,  7.96, 10.43,  4.12,  4.16,
        4.56, 12.44,  4.38,  3.91, 10.61,  1.42,  4.42,  7.91,  6.92,
        4.9 ,  6.85, 11.91,  0.91,  5.42,  5.21,  8.32,  7.32,  1.82,
        8.47,  7.8 ,  8.85, 13.39,  7.99,  9.46,  6.5 ,  5.52, 12.61,
        8.55, 10.64,  7.7 ,  4.43,  9.14,  8.01,  7.52, 11.62,  2.23,
        8.7 , 11.7 ,  6.56,  7.95,  5.33,  4.81,  4.53,  8.86,  8.39,
        5.58,  9.48,  7.45, 12.49,  4.88,  4.11,  5.3 ,  5.07,  4.62,
        5.55,  0.16,  3.47,  8.98,  9.  ,  6.62,  6.67,  6.01,  9.31,
        8.54,  8.8 ,  7.57,  7.37,  6.87, 11.67,  6.88,  8.19,  8.87,
        9.34, 11.27,  6.52,  4.96,  4.47,  8.41,  9.54,  7.62,  3.67,
        6.44,  5.17,

In [12]:
data.Sales.value_counts()

7.80     4
6.67     3
8.77     3
9.32     3
5.87     3
        ..
8.89     1
13.39    1
9.14     1
5.07     1
9.50     1
Name: Sales, Length: 336, dtype: int64

#### Decision Tree Regression Example

In [13]:
# Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor

In [14]:
array = data.values
array

array([[  9.5 , 138.  ,  73.  , ...,   1.  ,   0.  ,   0.  ],
       [ 11.22, 111.  ,  48.  , ...,   1.  ,   1.  ,   0.  ],
       [ 10.06, 113.  ,  35.  , ...,   1.  ,   0.  ,   1.  ],
       ...,
       [  7.41, 162.  ,  26.  , ...,   1.  ,   0.  ,   1.  ],
       [  5.94, 100.  ,  79.  , ...,   1.  ,   0.  ,   0.  ],
       [  9.71, 134.  ,  37.  , ...,   1.  ,   1.  ,   0.  ]])

In [15]:
X = array[:,0:12]
X

array([[  9.5 , 138.  ,  73.  , ...,   1.  ,   0.  ,   0.  ],
       [ 11.22, 111.  ,  48.  , ...,   1.  ,   1.  ,   0.  ],
       [ 10.06, 113.  ,  35.  , ...,   1.  ,   0.  ,   1.  ],
       ...,
       [  7.41, 162.  ,  26.  , ...,   1.  ,   0.  ,   1.  ],
       [  5.94, 100.  ,  79.  , ...,   1.  ,   0.  ,   0.  ],
       [  9.71, 134.  ,  37.  , ...,   1.  ,   1.  ,   0.  ]])

In [16]:
Y = array[:,0]
Y

array([ 9.5 , 11.22, 10.06,  7.4 ,  4.15, 10.81,  6.63, 11.85,  6.54,
        4.69,  9.01, 11.96,  3.98, 10.96, 11.17,  8.71,  7.58, 12.29,
       13.91,  8.73,  6.41, 12.13,  5.08,  5.87, 10.14, 14.9 ,  8.33,
        5.27,  2.99,  7.81, 13.55,  8.25,  6.2 ,  8.77,  2.67, 11.07,
        8.89,  4.95,  6.59,  3.24,  2.07,  7.96, 10.43,  4.12,  4.16,
        4.56, 12.44,  4.38,  3.91, 10.61,  1.42,  4.42,  7.91,  6.92,
        4.9 ,  6.85, 11.91,  0.91,  5.42,  5.21,  8.32,  7.32,  1.82,
        8.47,  7.8 ,  4.9 ,  8.85,  9.01, 13.39,  7.99,  9.46,  6.5 ,
        5.52, 12.61,  6.2 ,  8.55, 10.64,  7.7 ,  4.43,  9.14,  8.01,
        7.52, 11.62,  4.42,  2.23,  8.47,  8.7 , 11.7 ,  6.56,  7.95,
        5.33,  4.81,  4.53,  8.86,  8.39,  5.58,  9.48,  7.45, 12.49,
        4.88,  4.11,  6.2 ,  5.3 ,  5.07,  4.62,  5.55,  0.16,  8.55,
        3.47,  8.98,  9.  ,  6.62,  6.67,  6.01,  9.31,  8.54,  5.08,
        8.8 ,  7.57,  7.37,  6.87, 11.67,  6.88,  8.19,  8.87,  9.34,
       11.27,  6.52,

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [18]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [19]:
#Find the accuracy
model.score(X_test,y_test)

0.9892684503092246